name: flutter_warnet_fatur
description: "Project Warnet Fathurrahman Al Hafiz."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true